[platformio]
default_envs = Apollo_M-1-Rev2

[env:Apollo_M-1]
extends = env:esp32S3_8MB_PSRAM_M 
board = lilygo-t7-s3 ;; closer match for PSRAM and Flash size
board_build.partitions = ${esp32.extreme_partitions}    ;; default 16MB WLED partitions


build_unflags = ${env:esp32S3_8MB_M.build_unflags}   ;; use the same as "normal" S3 buildenv
  ; -D ARDUINO_USB_CDC_ON_BOOT=1                       ;; fix warning: "ARDUINO_USB_CDC_ON_BOOT" redefined; comment out for Serial debug
  ${Speed_Flags.build_unflags}  ;; to override -Os
build_flags = ${common.build_flags} ${esp32s3.build_flags} -Wno-misleading-indentation -Wno-format-truncation
  ${common_mm.build_flags_S}
  ${Speed_Flags.build_flags_V4}  ;; -O2 -> optimize for speed instead of size
  -D WLED_RELEASE_NAME=Apollo_M-1
  -D SERVERNAME='"Apollo M-1"'
  ; Serial debug enabled
  -DARDUINO_USB_MODE=1 -DARDUINO_USB_CDC_ON_BOOT=1 -DARDUINO_USB_MSC_ON_BOOT=0 -DARDUINO_USB_DFU_ON_BOOT=1 ;; for Hardware-CDC USB mode
  ; -D ARDUINO_USB_CDC_ON_BOOT=0
  -D WLED_DISABLE_ADALIGHT     ;; disables serial protocols - recommended for Hardware-CDC USB (Serial RX will receive junk commands when RX pin is unconnected, unless its pulled down by resistor)
  ; ${common_mm.animartrix_build_flags}
  ${common_mm.build_disable_sync_interfaces}
  -D LOLIN_WIFI_FIX ;; try this in case Wifi does not work
  -D WLED_WATCHDOG_TIMEOUT=0 -D CONFIG_ASYNC_TCP_USE_WDT=0
  -D WLED_USE_PSRAM -DBOARD_HAS_PSRAM ; tells WLED that PSRAM shall be used
  -D WLED_USE_PSRAM_JSON -DALL_JSON_TO_PSRAM ; WLEDMM --> force all JSON stuff into PSRAM; gives more free heap
  ; -DCONFIG_MBEDTLS_DYNAMIC_BUFFER=1 ;; optional - seems to move more buffers into PSRAM
  ${common_mm.HUB75_build_flags}
  -D DEFAULT_LED_TYPE=103 ; Hub75 64x64
  -D SR_DMTYPE=1 -D I2S_SDPIN=16 -D I2S_CKPIN=7 -D I2S_WSPIN=6 -D MCLK_PIN=-1  ;; I2S mic
  -D ABL_MILLIAMPS_DEFAULT=0 ;; disable ABL by default, as it does not work with Hub75
  -D WLED_DEBUG
  -D MOONHUB_S3_PINOUT ;; HUB75 pinout



lib_deps = ${esp32s3.lib_deps} ${common_mm.lib_deps_S} ;; ;;  do not include ${esp32.lib_depsV4} !!!!
  ; ${common_mm.animartrix_lib_deps}
  ${common_mm.HUB75_lib_deps}

lib_ignore = IRremoteESP8266 ; use with WLED_DISABLE_INFRARED for faster compilation
monitor_filters = esp32_exception_decoder

[env:Apollo_M-1-Rev2]
; This is the environment for the Apollo M-1 Rev2 board, which has 16MB Flash and 8MB PSRAM, but no pin conflict between octal PSRAM and Hub75.
extends = env:Apollo_M-1
board = adafruit_matrixportal_esp32s3 ;; wrong Flash size, but no pin conflict between octal PSRAM and Hub75
platform = ${esp32.platformV4_xp} ;; 6.5.0 = first platform release supporting matrixportal
platform_packages = ${esp32.platformV4_packages_xp}

board_build.partitions = ${esp32.large_partitions}
board_build.arduino.memory_type = qio_qspi 

build_unflags = ${env:Apollo_M-1.build_unflags}
  -D MOONHUB_S3_PINOUT ;; HUB75 pinout
  -D WLED_RELEASE_NAME=Apollo_M-1

build_flags = ${env:Apollo_M-1.build_flags} 
  -D ARDUINO_ADAFRUIT_MATRIXPORTAL_ESP32S3 ;; Needed to keep the pinout you are using on your board
  -D WLED_RELEASE_NAME=Apollo_M-1-Rev2
