[platformio]
default_envs = 
	gledopto
	gledopto_eth

[custom_flags]
build_flags =
 -D WLED_BRAND="\"GLEDOPTO\""
 -D SERVERNAME='"WLED-Gledopto"'

[env:gledopto]
extends = env:esp32dev
build_unflags = ${env:esp32dev.build_unflags}
 -D WLED_RELEASE_NAME
build_flags = ${env:esp32dev.build_flags}
 ${custom_flags.build_flags}
 -D SERVERNAME='"WLED-Gledopto"'
 -D WLED_PRODUCT_NAME="\"GLED\""
 -D WLED_RELEASE_NAME="\"ESP32\""

[env:gledopto_eth]
extends = env:esp32dev
build_unflags = ${env:esp32dev.build_unflags}
 -D WLED_RELEASE_NAME
build_flags = ${env:esp32dev.build_flags}
 ${custom_flags.build_flags}
 -D WLED_PRODUCT_NAME="\"GLED_Ethernet\""
 -D WLED_RELEASE_NAME="\"ESP32_Ethernet\""
# Gledopto Ethernet
 -D WLED_ETH_DEFAULT=13 
