[platformio]
default_envs = LavaLamp 

[env:LavaLamp]
board = esp32dev
extends = env:esp32_4MB_V4_S
board_build.partitions = ${esp32.default_partitions} ;; compatible with upstream
build_unflags = ${esp32_4MB_V4_S_base.build_unflags}
               -D WLED_RELEASE_NAME=esp32_4MB_V4_S
               ${common_mm.DMXin_build_flags} ;; exceeds flash size limits
               -D WLED_ENABLE_HUB75MATRIX     ;; no need
               -D WLED_ENABLE_GIF             ;; -28KB: inherited from build_flags_S, not needed for LavaLamp
               -D WLED_ENABLE_PIXELFORGE      ;; -12KB: inherited from parent env, not needed
build_flags = ${esp32_4MB_V4_S_base.esp32_build_flags}
  ; ${Speed_Flags.build_flags}  ;; -O2 -> optimize for speed instead of size
  ${common_mm.build_flags_S}
  -D WLED_RELEASE_NAME=LavaLamp
  -D WLED_DISABLE_ADALIGHT     ;; disables serial protocols - recommended for Hardware-CDC USB (Serial RX will receive junk commands when RX pin is unconnected, unless its pulled down by resistor)
  ${common_mm.animartrix_build_flags}
  -D WLED_DISABLE_LOXONE ; FLASH 1272 bytes
  -D WLED_DISABLE_MQTT ;   RAM 216 bytes; FLASH 16496 bytes
  -D WLED_DISABLE_INFRARED ;RAM 136 bytes; FLASH 24492 bytes
  -D USERMOD_AUTO_SAVE
  -D DEFAULT_LED_COUNT=256
  -D SR_DMTYPE=1 -D I2S_SDPIN=22 -D I2S_WSPIN=21 -D I2S_CKPIN=17
  -D SR_SQUELCH=10 -D SR_GAIN=60 -D SR_FREQ_PROF=2
  -D WLED_AP_SSID_UNIQUE
  -D ABL_MILLIAMPS_DEFAULT=1800
  -D SERVERNAME='"MillliWatt-LavaLamp"'
  -D UM_AUDIOREACTIVE_ENABLE
  ; -D WLED_DEBUG
  ; -D SR_DEBUG
  ; -D MIC_LOGGER
  -D WLED_DISABLE_ALEXA
  -D WLED_DISABLE_HUESYNC
  -D WLED_DISABLE_ESPNOW  ;; might help in case of WiFi connectivity problems
  -D WLED_DISABLE_PARTICLESYSTEM1D ;; exceeds flash size limit
  -D WLED_DISABLE_PARTICLESYSTEM2D ;; exceeds flash size limit

lib_deps =
  ${esp32_4MB_V4_S_base.esp32_lib_deps}  ;; AsyncTCP + NeoPixelBus + HUB75 + env.lib_deps + lib_deps_S + DMXin
  ${common_mm.animartrix_lib_deps}
lib_ignore =
  IRremoteESP8266
  ${common_mm.HUB75_lib_ignore}
  ${common_mm.DMXin_lib_ignore}

[env:241Rings]
board = esp32dev
extends = esp32_4MB_S_base
build_unflags = ${esp32_4MB_S_base.build_unflags}
  ${Speed_Flags.build_unflags}  ;; to override -Os
  -D WLED_DISABLE_HUESYNC
  -D WLED_DISABLE_ALEXA ;  RAM 116 bytes; FLASH 13524 bytes
build_flags = ${esp32_4MB_S_base.build_flags}
  ${Speed_Flags.build_flags}  ;; -O2 -> optimize for speed instead of size
  ${common_mm.build_flags_S}
  -D WLED_RELEASE_NAME=241Rings
  -D WLED_DISABLE_ADALIGHT     ;; disables serial protocols - recommended for Hardware-CDC USB (Serial RX will receive junk commands when RX pin is unconnected, unless its pulled down by resistor)
  -D WLED_DISABLE_LOXONE ; FLASH 1272 bytes
  -D WLED_DISABLE_MQTT ;   RAM 216 bytes; FLASH 16496 bytes
  -D WLED_DISABLE_INFRARED ;RAM 136 bytes; FLASH 24492 bytes
  -D USERMOD_AUTO_SAVE
  -D DEFAULT_LED_COUNT=241
  -D WLED_AP_SSID_UNIQUE
  -D ABL_MILLIAMPS_DEFAULT=1800
  -D SERVERNAME='"MillliWatt-241Rings"'
  -D UM_AUDIOREACTIVE_ENABLE
  -D USERMOD_241RINGS
  -D SR_DMTYPE=254 -D I2S_SDPIN=-1 -D I2S_WSPIN=-1 -D I2S_CKPIN=-1 ;; Disable mic

lib_deps = ${esp32.lib_deps} ${common_mm.lib_deps_S}
lib_ignore = IRremoteESP8266 ; use with WLED_DISABLE_INFRARED for faster compilation
