name: WLED CI

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  wled_build:
    uses: ./.github/workflows/build.yml

  changelog:
    name: Update Changelog
    runs-on: ubuntu-latest
    steps:
      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v5.0.0
